name: kyma-project.io/module/registry-proxy
version: main
defaultCR: default-registry-proxy-cr.yaml
manifest: registry-proxy-operator.yaml
# TODO: upload documentation
documentation: "https://github.com/kyma-project/registry-proxy/blob/main/docs/user/README.md"
repository: https://github.com/kyma-project/registry-proxy.git
security: sec-scanners-config.yaml
manager:
  name: registry-proxy-operator
  group: apps
  version: v1
  kind: Deployment
associatedResources:
  - group: operator.kyma-project.io
    kind: RegistryProxy
    version: v1alpha1
  - group: registry-proxy.kyma-project.io
    kind: Connection
    version: v1alpha1
icons:
  - name: module-icon
    #TODO: Provide icon for registry-proxy
    link: https://raw.githubusercontent.com/kyma-project/kyma/refs/heads/main/docs/assets/logo_icon.svg
team: kyma/Otters
