name: integration tests

on:
  workflow_call:
    inputs:
      operator_image:
        description: "The operator image to test"
        required: true
        type: string
      rp_image:
        description: "The registry-proxy image to test"
        required: true
        type: string
      connection_image:
        description: "The connection image to test"
        required: true
        type: string

jobs:
  operator-integration-test:
    if: ${{ !startsWith(github.event_name, 'pull_request') || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: kyma-project/manager-toolkit/.github/actions/setup-go@main
      - name: compute github commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: kyma-project/manager-toolkit/.github/actions/create-k3d-cluster@main
      - name: run test
        run: |
          CLI_TMPDIR=cli-$(date "+%Y-%m-%d_%H:%M:%S")
          mkdir -p ${CLI_TMPDIR}
          VERSION=$(curl -H "Authorization: Bearer ${BOT_TOKEN}" -s https://api.github.com/repos/kyma-project/cli/releases/latest | jq -r '.tag_name')
          echo "Downloading https://github.com/kyma-project/cli/releases/download/${VERSION}/kyma_$(uname -s)_$(uname -m).tar.gz"
          curl -sL "https://github.com/kyma-project/cli/releases/download/${VERSION}/kyma_$(uname -s)_$(uname -m).tar.gz" -o ${CLI_TMPDIR}/cli.tar.gz
          echo "unpacking kyma cli"
          tar --force-local -zxvf ${CLI_TMPDIR}/cli.tar.gz kyma
          mkdir -p ./bin
          mv kyma ./bin/kyma
          echo "removing ${CLI_TMPDIR}"
          rm -r ${CLI_TMPDIR}
          PATH=$(pwd)/bin:$PATH
          echo "path: ${PATH}"
          export PATH
          kubectl create namespace kyma-system || true
          make -C components/operator install-registry-proxy-operator
          make run-integration-test-operator
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OPERATOR_IMG: ${{ inputs.operator_image }}
          CONNECTION_IMG: ${{ inputs.connection_image }}
          RP_IMG: ${{ inputs.rp_image }}
      - if: ${{ always() }}
        uses: ./.github/actions/collect-cluster-info
  registry-proxy-integration-test:
    if: ${{ !startsWith(github.event_name, 'pull_request') || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: kyma-project/manager-toolkit/.github/actions/setup-go@main
      - name: compute github commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: kyma-project/manager-toolkit/.github/actions/create-k3d-cluster@main
      - name: run test
        run: |
          CLI_TMPDIR=cli-$(date "+%Y-%m-%d_%H:%M:%S")
          mkdir -p ${CLI_TMPDIR}
          VERSION=$(curl -H "Authorization: Bearer ${BOT_TOKEN}" -s https://api.github.com/repos/kyma-project/cli/releases/latest | jq -r '.tag_name')
          echo "Downloading https://github.com/kyma-project/cli/releases/download/${VERSION}/kyma_$(uname -s)_$(uname -m).tar.gz"
          curl -sL "https://github.com/kyma-project/cli/releases/download/${VERSION}/kyma_$(uname -s)_$(uname -m).tar.gz" -o ${CLI_TMPDIR}/cli.tar.gz
          echo "unpacking kyma cli"
          tar --force-local -zxvf ${CLI_TMPDIR}/cli.tar.gz kyma
          mkdir -p ./bin
          mv kyma ./bin/kyma
          echo "removing ${CLI_TMPDIR}"
          rm -r ${CLI_TMPDIR}
          PATH=$(pwd)/bin:$PATH
          echo "path: ${PATH}"
          export PATH
          make -C components/operator install-registry-proxy-operator
          kubectl create namespace kyma-system || true
          kubectl apply -f config/samples/default-registry-proxy-cr.yaml
          make run-integration-test-registry-proxy
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OPERATOR_IMG: ${{ inputs.operator_image }}
          CONNECTION_IMG: ${{ inputs.connection_image }}
          RP_IMG: ${{ inputs.rp_image }}
      - if: ${{ always() }}
        uses: ./.github/actions/collect-cluster-info
