name: check manifests
on:
  pull_request:

jobs:
  check-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: kyma-project/manager-toolkit/.github/actions/setup-go@main

      - name: Run make generate manifests
        run: make generate manifests

      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Manifests are not up to date. Run 'make generate manifests' and commit the changes."
            git diff
            exit 1
          fi
